version: '3'
services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: todo_postgres_pass
      POSTGRES_DB: todo_app_db
    ports:
      - 5432:5432
