version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    depends_on:
      - app
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: todo_postgres_pass
      POSTGRES_DB: todo_app_db
    ports:
      - 5432:5432
